### ISSUE TITLE
Internship homepage

### ISSUE THREAD

**Issue by JacobWangTengda** [pelican2014/NUS-Lighthouse#75]
Components Needed:
- Search Bar
- Recommended for you
- Tabs and Dropdown List in the Explore by Section
- Main Charts

##### Route: 
- Search Bar --> Specific Internship Position
- Recommended for you ---> Specific Internship Position
- Explore by: (include drop down list)
- Industry --> Industry Page
- Major --> ????
- Company ---> Company Page

**Comment by tongyao-zhu** [comment]
What should be displayed from the Major Tab?
How can we go from the Major Tab to elsewhere?
